---
title: "Workshop Environment Setup"
subtitle: "Screenshots"
author: "Eric Nantz"
footer: "[{{< var workshop_short_url >}}]({{< var workshop_full_url >}})"
format: 
  revealjs:
    theme: [default, ../slides.scss] # moon= teal bg  |  dark
    scrollable: true
    incremental: true
    slide-number: c/t # c/t | c | h/v | h.v
    slide-tone: false #true
    code-line-numbers: false
    history: true
---

# Create Posit Connect Account

## {background-image="assets/screenshots/psconnect_login_1.png" background-size="contain"}

## {background-image="assets/screenshots/psconnect_login_2.png" background-size="contain"}

## {background-image="assets/screenshots/psconnect_login_3.png" background-size="contain"}

# Create Posit Connect API Key 

## {background-image="assets/screenshots/psconnect_apikey_1.png" background-size="contain"}

## {background-image="assets/screenshots/psconnect_apikey_2.png" background-size="contain"}

## {background-image="assets/screenshots/psconnect_apikey_3.png" background-size="contain"}

# Posit Cloud Setup

## {background-image="assets/screenshots/pscloud_1.png" background-size="contain"}

## {background-image="assets/screenshots/pscloud_2.png" background-size="contain"}

## {background-image="assets/screenshots/pscloud_3.png" background-size="contain"}

## {background-image="assets/screenshots/pscloud_4.png" background-size="contain"}

# Account Integrations

## {background-image="assets/screenshots/account_integrate_1.png" background-size="contain"}

## {background-image="assets/screenshots/account_integrate_2.png" background-size="contain"}

## {background-image="assets/screenshots/account_integrate_3.png" background-size="contain"}

## {background-image="assets/screenshots/account_integrate_4.png" background-size="contain"}

## {background-image="assets/screenshots/account_integrate_5.png" background-size="contain"}

## {background-image="assets/screenshots/account_integrate_6.png" background-size="contain"}